version: "2"
services:
  server:
      build: 
        context: ../preferans-server
        dockerfile: Dockerfile
      ports:
        - 8080:8080
  nginx-react:
    container_name: ngixreactapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production
