version: "3.4"
services:
  backend:
    build: 
      context: ../preferans-server
      dockerfile: Dockerfile
    environment:
      - CLIENT_IP=77.105.174.80
    ports:
     - 80:80
     - 443:443
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      NODE_ENV: production
  certbot:
    image: certbot/certbot
    volumes:
      -  /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email n.savchenkoo73@gmail.com --agree-tos --no-eff-email --force-renewal -d woo-preferans.ru -d www.woo-preferans.ru -d woo-preferans.online -d woo-preferans.online 

