version: "3.4"
services:
  backend:
    build: 
      context: ../preferans-server
      dockerfile: Dockerfile
    environment:
      - CLIENT_URL=https:woo-preferans.ru
      - SPRING_PROFILES_ACTIVE=production
    ports:
     - 8086:8086
     - 8443:8443
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=https://woo.preferans.onine:8443/api/v1
      - VITE_SOCKET_BASE_URL=https://woo.preferans.online:8086
  certbot:
    image: certbot/certbot
    volumes:
      -  /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email n.savchenkoo73@gmail.com --agree-tos --no-eff-email --force-renewal -d woo-preferans.ru -d www.woo-preferans.ru -d woo-preferans.online -d woo-preferans.online 

